### ISSUE TITLE
MySQL connect assumed localhost (socket connection)

### ISSUE THREAD

**Issue by cytopia** [photoncms/installer#2]
I am trying to use this photon cli to install a new CMS from scratch, however it only asks for MySQL username and password and simply assumes that MySQL is running on `localhost` (connection via MySQL socket != `127.0.0.1`):

https://github.com/photoncms/installer/blob/master/src/Installer.php#L321

Can you make this a command line option as well or ask for the hostname during installation.

**Comment by tihomiro** [comment]
That's a good point, will fix. Thanks.

**Comment by tihomiro** [comment]
Fixed in https://github.com/photoncms/installer/releases/tag/v1.0.4
